POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/dd039fd5-c98d-4ac6-960a-329517a08907/attendees
Content-Type: application/json

{
  "name": "Oliver Mayer",
  "email": "olivermayer@gmail.com"
}

###

GET http://localhost:3333/events/dd039fd5-c98d-4ac6-960a-329517a08907

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/dd039fd5-c98d-4ac6-960a-329517a08907/attendees?query=Oliver